language: generic
deploy:
  provider: s3
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY"
  bucket: my-ml-workshop
  on:
    repo: hafizar99/sagemaker-learn
